blank_issues_enabled: false

contact_links:
  - name: âœ¨ ê¸°ëŠ¥ ê°œë°œ ìš”ì²­
    url: https://github.com/poc-kpfis-back-service/issues/new?template=feat--ê¸°ëŠ¥-ê°œë°œ.md
    about: ìƒˆë¡œìš´ ê¸°ëŠ¥ì„ ê°œë°œí•˜ê³  ì‹¶ì„ ë•Œ

  - name: ğŸ ë²„ê·¸ ë¦¬í¬íŠ¸
    url: https://github.com/poc-kpfis-back-service/issues/new?template=bug--ë²„ê·¸-ë¦¬í¬íŠ¸.md
    about: ë¬¸ì œë¥¼ ë°œê²¬í–ˆì„ ë•Œ

  - name: ğŸ”§ ê¸°ëŠ¥ ìˆ˜ì • / ê°œì„ 
    url: https://github.com/poc-kpfis-back-service/issues/new?template=fix--ê¸°ëŠ¥-ìˆ˜ì •.md
    about: ê¸°ì¡´ ê¸°ëŠ¥ì˜ ë™ì‘ì„ ìˆ˜ì •í•˜ê±°ë‚˜ ê°œì„ í•˜ê³  ì‹¶ì„ ë•Œ

  - name: ğŸ“˜ ë¬¸ì„œ ìˆ˜ì •
    url: https://github.com/poc-kpfis-back-service/issues/new?template=docs--ë¬¸ì„œ-ìˆ˜ì •.md
    about: README, Wiki, API ë¬¸ì„œ ë“±ì˜ ìˆ˜ì • ë˜ëŠ” ê°œì„ 
